apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: acr-
commonLabels:
  app: acr-credentials-sync

namespace: flux-system

resources:
- ../_base
- az-identity.yaml

patches:
- path: config-map-patch.yaml
- path: azure-identity-patch.yaml
- path: token-refresh-and-identity-injection-patch.yaml
- path: reconcile-patch.yaml

vars:
- name: AZ_IDENTITY_NAME
  objref:
    kind: AzureIdentity
    name: credentials-sync
    apiVersion: aadpodidentity.k8s.io/v1

configurations:
- kustomizeconfig.yaml
