apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/fluxcd/source-watcher/releases/download/v2.0.2/source-watcher.crds.yaml
- https://github.com/fluxcd/source-watcher/releases/download/v2.0.2/source-watcher.deployment.yaml
- account.yaml
transformers:
- labels.yaml
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: source-watcher
  path: patch.yaml
