apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: gcr-
commonLabels:
  app: gcr-credentials-sync

namespace: flux-system

resources:
- ../_base

patches:
- path: config-map-patch.yaml
- path: bind-irsa-patch.yaml
- path: gcr-token-refresh-patch.yaml
- path: reconcile-patch.yaml
